export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_ITEM_IN_CART = 'DELETE_ITEM_IN_CART';
export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';
